version: '3.8'

services:
  db:
    image: postgres:16 
    container_name: postgres_db_servidor_auditoria 
    restart: always 
    environment:
      POSTGRES_DB: filesdb 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    ports:

      - "5432:5432"
    volumes:

      - pg_data_c1_auditoria:/var/lib/postgresql/data

      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      
      - db-network-c1

volumes:
  
  pg_data_c1_auditoria:

networks:
  
  db-network-c1:
    driver: bridge