services:
  app: 
    build: . 
    container_name: app_combinada_servidor_auditoria
    restart: always
    ports:
      - "8080:3000"
    volumes:
      - app_uploads_auditoria:/app/uploads 
    networks:
      - app-network

volumes:
  app_uploads_auditoria:

networks:
  app-network:
    driver: bridge